[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon_mainnet = "${POLYGON_MAINNET_RPC_URL}"
polygon_testnet = "${POLYGON_TESTNET_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[fmt]
line_length = 120
tab_width = 2
single_line_statement_blocks = "single"
multiline_func_header = "params_first"
sort_imports = true
contract_new_lines = true
override_spacing = false
number_underscore = "thousands"
wrap_comments = true

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon_mainnet = { key = "${POLYGONSCAN_API_KEY}" }
polygon_testnet = { key = "${POLYGONSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }

[profile.default.fs_permissions]
"rules/" = "read"